import Footer from "./components/common/Footer";
import Header from "./components/common/Header";
import { WebVitals } from "./components/WebVitals";
import "./globals.css";

export const metadata = {
  title: {
    default: 'Next.js Learn',
    template: '%s | Next.js Learn',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                {/* <WebVitals /> */}
                <Header/>
                {children}
                <Footer />
            </body>
        </html>
  );
}
