import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "next-intl/server";
import {notFound} from "next/navigation";
import {routing} from "@/i18n/routing";
import "../globals.css";
import Header from "../components/common/Header";
import Footer from "../components/common/Footer";


export const metadata = {
  title: {
    default: 'Next.js Learn',
    template: '%s | Next.js Learn',
  },
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}));
}

export default async function LocaleLayout({
  children,
  params
}) {

  const {locale} = await params;

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>

        <NextIntlClientProvider messages={messages}>
            <Header />
            {children}
            <Footer />
        </NextIntlClientProvider>

      </body>
    </html>
  );
}